# This is a basic workflow to help you get started with Actions

name: production

on:
    push:
        branches: ["production"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Publish Latest to Registry
              uses: elgohr/Publish-Docker-Github-Action@master
              with:
                  name: KATITB22/Backend/production
                  username: ${{ secrets.PKG_REGISTRY_USERNAME }}
                  password: ${{ secrets.PKG_REGISTRY_PASSWORD }}
                  registry: docker.pkg.github.com
                  tags: "latest"
    deploy:
        runs-on: ubuntu-latest
        needs: [build]
        steps:
            - name: Deployment
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.PROD_HOST_ADDRESS }}
                  username: ${{ secrets.PROD_HOST_USERNAME }}
                  password: ${{ secrets.PROD_HOST_PASSWORD }}
                  script: |
                      cd server
                      docker-compose pull
                      docker-compose up -d --remove-orphans
                      docker image prune -f
