# This is a basic workflow to help you get started with Actions

name: staging

on:
    push:
        branches: ["development"]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Publish Latest to Registry
              uses: elgohr/Publish-Docker-Github-Action@master
              with:
                  name: KATITB22/Backend/development
                  username: ${{ secrets.PKG_REGISTRY_USERNAME }}
                  password: ${{ secrets.PKG_REGISTRY_PASSWORD }}
                  registry: docker.pkg.github.com
                  tags: "latest"
    deploy:
        runs-on: ubuntu-latest
        needs: [build]
        steps:
            - name: Deployment
              uses: cross-the-world/ssh-scp-ssh-pipelines@latest
              with:
                  host: ${{ secrets.STAGING_HOST_ADDRESS }}
                  user: ${{ secrets.STAGING_HOST_USERNAME }}
                  pass: ${{ secrets.STAGING_HOST_PASSWORD }}
                  connect_timeout: 10s
                  first_ssh: |
                      cd server
                      docker-compose pull
                      docker-compose up -d --remove-orphans
                      docker image prune -f
    check-status:
        runs-on: ubuntu-latest
        needs: [deploy]
        steps:
            - name: Backend Status
              uses: cygnetdigital/wait_for_response@v2.0.0
              with:
                  url: "https://api.staging.katitb22.com"
                  responseCode: "200"
                  timeout: "75000"
                  interval: "1000"
